// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	domain "grail-participant-registry/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ParticipantRepository is an autogenerated mock type for the ParticipantRepository type
type ParticipantRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: participant
func (_m *ParticipantRepository) Add(participant domain.Participant) error {
	ret := _m.Called(participant)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Participant) error); ok {
		r0 = rf(participant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *ParticipantRepository) FindAll() ([]domain.Participant, error) {
	ret := _m.Called()

	var r0 []domain.Participant
	if rf, ok := ret.Get(0).(func() []domain.Participant); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Participant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByRef provides a mock function with given fields: participantRef
func (_m *ParticipantRepository) FindByRef(participantRef domain.ParticipantReference) (domain.Participant, error) {
	ret := _m.Called(participantRef)

	var r0 domain.Participant
	if rf, ok := ret.Get(0).(func(domain.ParticipantReference) domain.Participant); ok {
		r0 = rf(participantRef)
	} else {
		r0 = ret.Get(0).(domain.Participant)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.ParticipantReference) error); ok {
		r1 = rf(participantRef)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: participantRef
func (_m *ParticipantRepository) Remove(participantRef domain.ParticipantReference) error {
	ret := _m.Called(participantRef)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.ParticipantReference) error); ok {
		r0 = rf(participantRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: participant
func (_m *ParticipantRepository) Update(participant domain.Participant) error {
	ret := _m.Called(participant)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Participant) error); ok {
		r0 = rf(participant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
